
services:
  # 1. PostgreSQL Database (For storing permanent data like user accounts/orders)
  postgres:
    image: postgres:15
    container_name: trading-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tradingdb
      TZ: Asia/Kolkata
      GTZ: Asia/Kolkata
    ports:
      - "5433:5432"

  # 2. Redis (For fast, temporary in-memory caching)
  redis:
    image: redis:7
    container_name: trading-redis
    ports:
      - "6379:6379"

  # 3. Zookeeper (Kafka needs this to manage its nodes)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: trading-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # 4. Kafka (The message broker for real-time trading events)
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: trading-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1